spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/testsecurity
    username: testsecurity
    password: '0000'
    driver-class-name: org.mariadb.jdbc.Driver

